### ISSUE TITLE
prometheus_client_php v2.1.1 RenderTextFormat fails with an array_combine warning

### ISSUE THREAD

**Issue by derekrodrigueswunderkind** [PromPHP/prometheus_client_php#19]
Issue:
When rendering metrics, I encountered this error:
`Warning: array_combine(): Both parameters should have an equal number of elements in /var/www/vendor/promphp/prometheus_client_php/src/Prometheus/RenderTextFormat.php:43`

Code Excerpt:
```
$adapter           = new Redis();
$collectorRegistry = new CollectorRegistry($adapter);

$renderer = new RenderTextFormat();
$result   = $renderer->render($collectorRegistry->getMetricFamilySamples());

return new Response($result, 200, ['Content-Type' => RenderTextFormat::MIME_TYPE]);
```

Stack:
```
Symfony\Component\Debug\Exception\ContextErrorException: Warning: array_combine(): Both parameters should have an equal number of elements in /var/www/vendor/promphp/prometheus_client_php/src/Prometheus/RenderTextFormat.php:43
Stack trace:
#0 /var/www/vendor/promphp/prometheus_client_php/src/Prometheus/RenderTextFormat.php(26): Prometheus\RenderTextFormat->renderSample(Object(Prometheus\MetricFamilySamples), Object(Prometheus\Sample)) #1 /var/www/src/Controller/Metrics.php(39): Prometheus\RenderTextFormat->render(Array)
#2 /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): BounceX\Core\Controller\Metrics->getMetrics(Object(Symfony\Component\HttpFoundation\Request))
#3 /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/web/index.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 {main} [] []
```

Steps to reproduce:
After encountering this error, I restarted both my php-fpm and redis docker instances, and unfortunately, no longer able to reproduce. I don't have any STR.

Stack:
- prometheus_client_php v2.1.1
- php-fpm
- symfony v3.4.2
- php v7.2

**Comment by LKaemmerling** [comment]
Hey @derekrodrigueswunderkind,

thank you for the report. I had a look into the code and it looks like the definition/registration of one(or more) of your metrics contains more or less labels than your value setting:

Sample:
```php
$counter = $registry->registerCounter('test', 'some_counter', 'it increases', ['type', 'another_label']); // Here you define two labels
$counter->incBy(5, ['blue']); // Here you only set one label value

**Comment by derekrodrigueswunderkind** [comment]
Hi @LKaemmerling 
Thank you for the prompt follow-up.

That makes sense. It is probable I changed labels during development and neglected to restart redis, resulting in the mismatch.

Thank you.
